services:
  curriculum-vitae:
    image: ghcr.io/dominik-97/curriculum-vitae:latest
    container_name: curriculum-vitae
    restart: unless-stopped
    labels:
      # Traefik configuration
      - traefik.enable=true
      - traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${TRAEFIK_HOST}`)
      - traefik.http.routers.${SUBDOMAIN}.entrypoints=websecure
      - traefik.http.routers.${SUBDOMAIN}.tls.certresolver=letsencrypt
      - traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=80
    environment:
      - TZ=UTC
